#########################################################################
# File Name: conf/service.yaml
# Author: suixibing
# Desc: install package
# Created Time: Fri Apr  9 23:42:21 2021
#########################################################################
# service.yaml

global:                                              #全局配置
  database: mysql                                    #服务使用的数据库
  app: IM-xixi                                       #服务的应用名
  appPath: /usr/local/app                            #应用的存放地址

  #http通用配置
  usehttps: false                                    #是否使用https
  httpsCrt: ./server.crt                             #crt文件位置
  httpsKey: ./server.key                             #key文件位置

  #数据库通用设置
  showSQL: true                                      #显示执行的SQL语句
  maxOpenConns: 3                                    #最大同时连接数

services:                                            #服务配置
  - id: 1                                            #服务的编号
    port: 8080                                       #服务监听的端口
    LogLevel: info                                   #日志级别
    log:
      TimeTagFormat: "200601021504"
      LogPath: /usr/local/app/IM-xixi/log
      FileName: chatlog
      # MaxRemain will auto clear the roling file list, set 0 will disable auto clean
      MaxRemain: -1

      # RollingPolicy give out the rolling policy
      # We got 3 policies(actually, 2)
      # WithoutRolling(0) no rolling will happen
      # TimeRolling(1) rolling by time
      # VolumeRolling(2) rolling by file size
      RollingPolicy: 1
      RollingTimePattern: "0 0 0 * * *"
      RollingVolumeSize: 1G

      # WriterMode in 4 modes below
      # 1. none 2. lock
      # 3. async 4. buffer
      WriterMode: lock
      
      # BufferWriterThershould in Byte
      BufferWriterThershould: 64
      # Compress will compress log file with gzip
      Compress: false

database:                                            #数据库配置
  mysql:                                             #mysql配置
    host: 127.0.0.1                                  #mysql的host
    port: 3306                                       #mysql的端口号
    user: root                                       #mysql的登陆用户
    password: "123456"                               #用户的密码
    database: chat_xixi                              #使用的数据库名称
